version: "3.9"
services:
  grimm-redis:
    image: redis:7.2.3-alpine
    container_name: grimm-redis
    command: redis-server --save 300 1 --loglevel warning --port 6379
    restart: always
    #expose:
      #- 6379
    #ports:
      #- "6379:6379"
    networks:
      - host-network
    volumes:
      - cache:/data
  grimm-api:
    depends_on:
      - grimm-redis
    build: .
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - host-network
    restart: always

networks:
  host-network:
    driver: bridge

volumes:
  cache:
    driver: local
