version: "3.9"
services:
  grimm-redis:
    image: redis:7.2.3-alpine
    container_name: grimm-redis
    command: --port 6379
    expose:
      - 6379
    ports:
      - "6379:6379"
    networks:
      - host-network
  grimm-api:
    depends_on:
      - grimm-redis
    build: .
    expose:
      - 8000
    ports:
      - "8000:8000"
    networks:
      - host-network

networks:
  host-network:
    driver: bridge
